sudo: false
language: node_js
matrix:
  allow_failures:
    - node_js: "iojs"
node_js:
  - "0.12"
after_success:
  - "npm run func"
  - "cat artifacts/lcov.info | ./node_modules/coveralls/bin/coveralls.js" 
